### ISSUE TITLE
Request for MIT license

### ISSUE THREAD

**Issue by evanvin** [mendab1e/SolrCountriesSynonyms#1]
@mendab1e this list is really extensive and helpful! I want to respect the work you put in, so I'm requesting a MIT license to be added to this repo please

**Comment by mendab1e** [comment]
Hi Evan, to be honest I already forgot that I've created this repo 😅. I am very glad that you found it helpful. I will add an MIT license for it in the near future.

**Comment by evanvin** [comment]
> Hi Evan, to be honest I already forgot that I've created this repo 😅. I am very glad that you found it helpful. I will add an MIT license for it in the near future.

YES!!!!!! 🎉  thank you so much. In the meantime, do I have permission to use this repo and `countries_synonyms.txt`?

**Comment by mendab1e** [comment]
Sure, please use it!
